export const countries = [
  { name: "Afghanistan", phoneCode: "93", nationality: "Afghan" },
  { name: "Albania", phoneCode: "355", nationality: "Albanian" },
  { name: "Algeria", phoneCode: "213", nationality: "Algerian" },
  {
    name: "American Samoa",
    phoneCode: "1 684",
    nationality: "American Samoan",
  },
  { name: "Andorra", phoneCode: "376", nationality: "Andorran" },
  { name: "Angola", phoneCode: "244", nationality: "Angolan" },
  { name: "Anguilla", phoneCode: "1 264", nationality: "Anguillan" },
  { name: "Antarctica", phoneCode: "672, 64", nationality: "Antarctican" },
  {
    name: "Antigua and Barbuda",
    phoneCode: "1 268",
    nationality: "Antiguan or Barbudan",
  },
  { name: "Argentina", phoneCode: "54", nationality: "Argentine" },
  { name: "Armenia", phoneCode: "374", nationality: "Armenian" },
  { name: "Aruba", phoneCode: "297", nationality: "Aruban" },
  {
    name: "Ascension Island",
    phoneCode: "247",
    nationality: "Ascension Islander",
  },
  { name: "Australia", phoneCode: "61", nationality: "Australian" },
  { name: "Austria", phoneCode: "43", nationality: "Austrian" },
  { name: "Azerbaijan", phoneCode: "994", nationality: "Azerbaijani" },
  { name: "Bahamas", phoneCode: "1 242", nationality: "Bahamian" },
  { name: "Bahrain", phoneCode: "973", nationality: "Bahraini" },
  { name: "Bangladesh", phoneCode: "880", nationality: "Bangladeshi" },
  { name: "Barbados", phoneCode: "1 246", nationality: "Barbadian" },
  { name: "Belarus", phoneCode: "375", nationality: "Belarusian" },
  { name: "Belgium", phoneCode: "32", nationality: "Belgian" },
  { name: "Belize", phoneCode: "501", nationality: "Belizean" },
  { name: "Benin", phoneCode: "229", nationality: "Beninese" },
  { name: "Bermuda", phoneCode: "1 441", nationality: "Bermudian" },
  { name: "Bhutan", phoneCode: "975", nationality: "Bhutanese" },
  { name: "Bolivia", phoneCode: "591", nationality: "Bolivian" },
  {
    name: "Bosnia and Herzegovina",
    phoneCode: "387",
    nationality: "Bosnian or Herzegovinian",
  },
  { name: "Botswana", phoneCode: "267", nationality: "Motswana" },
  { name: "Brazil", phoneCode: "55", nationality: "Brazilian" },
  {
    name: "British Virgin Islands",
    phoneCode: "1 284",
    nationality: "British Virgin Islander",
  },
  { name: "Brunei", phoneCode: "673", nationality: "Bruneian" },
  { name: "Bulgaria", phoneCode: "359", nationality: "Bulgarian" },
  { name: "Burkina Faso", phoneCode: "226", nationality: "Burkinabe" },
  { name: "Burma (Myanmar)", phoneCode: "95", nationality: "Burmese" },
  { name: "Burundi", phoneCode: "257", nationality: "Burundian" },
  { name: "Cambodia", phoneCode: "855", nationality: "Cambodian" },
  { name: "Cameroon", phoneCode: "237", nationality: "Cameroonian" },
  { name: "Canada", phoneCode: "1", nationality: "Canadian" },
  { name: "Cape Verde", phoneCode: "238", nationality: "Cape Verdean" },
  { name: "Cayman Islands", phoneCode: "1 345", nationality: "Caymanian" },
  {
    name: "Central African Republic",
    phoneCode: "236",
    nationality: "Central African",
  },
  { name: "Chad", phoneCode: "235", nationality: "Chadian" },
  { name: "Chile", phoneCode: "56", nationality: "Chilean" },
  { name: "China", phoneCode: "86", nationality: "Chinese" },
  {
    name: "Christmas Island",
    phoneCode: "61",
    nationality: "Christmas Islander",
  },
  {
    name: "Cocos (Keeling) Islands",
    phoneCode: "61",
    nationality: "Cocos Islander",
  },
  { name: "Colombia", phoneCode: "57", nationality: "Colombian" },
  { name: "Comoros", phoneCode: "269", nationality: "Comorian" },
  { name: "Congo", phoneCode: "242", nationality: "Congolese" },
  { name: "Cook Islands", phoneCode: "682", nationality: "Cook Islander" },
  { name: "Costa Rica", phoneCode: "506", nationality: "Costa Rican" },
  { name: "Croatia", phoneCode: "385", nationality: "Croatian" },
  { name: "Cuba", phoneCode: "53", nationality: "Cuban" },
  { name: "Cyprus", phoneCode: "357", nationality: "Cypriot" },
  { name: "Czech Republic", phoneCode: "420", nationality: "Czech" },
  {
    name: "Democratic Republic of the Congo",
    phoneCode: "243",
    nationality: "Congolese",
  },
  { name: "Denmark", phoneCode: "45", nationality: "Danish" },
  { name: "Djibouti", phoneCode: "253", nationality: "Djiboutian" },
  { name: "Dominica", phoneCode: "1 767", nationality: "Dominican" },
  {
    name: "Dominican Republic",
    phoneCode: "1 809, 1 829, 1 849",
    nationality: "Dominican",
  },
  { name: "Ecuador", phoneCode: "593", nationality: "Ecuadorian" },
  { name: "Egypt", phoneCode: "20", nationality: "Egyptian" },
  { name: "El Salvador", phoneCode: "503", nationality: "Salvadoran" },
  {
    name: "Equatorial Guinea",
    phoneCode: "240",
    nationality: "Equatorial Guinean",
  },
  { name: "Eritrea", phoneCode: "291", nationality: "Eritrean" },
  { name: "Estonia", phoneCode: "372", nationality: "Estonian" },
  { name: "Ethiopia", phoneCode: "251", nationality: "Ethiopian" },
  { name: "Fiji", phoneCode: "679", nationality: "Fijian" },
  { name: "Finland", phoneCode: "358", nationality: "Finnish" },
  { name: "France", phoneCode: "33", nationality: "French" },
  { name: "Germany", phoneCode: "49", nationality: "German" },
  { name: "Greece", phoneCode: "30", nationality: "Greek" },
  { name: "India", phoneCode: "91", nationality: "Indian" },
  { name: "Indonesia", phoneCode: "62", nationality: "Indonesian" },
  { name: "Indonesia", phoneCode: "62", nationality: "Indonesian" },
  { name: "Pakistan", phoneCode: "92", nationality: "Pakistani" },
  { name: "Sri Lanka", phoneCode: "94", nationality: "Sri Lankan" },
  { name: "Spain", phoneCode: "34", nationality: "Spanish" },
  { name: "Turkey", phoneCode: "90", nationality: "Turkish" },
  { name: "Switzerland", phoneCode: "41", nationality: "Swiss" },
  { name: "Thailand", phoneCode: "66", nationality: "Thai" },
  { name: "Sweden", phoneCode: "46", nationality: "Swedish" },
  { name: "South Korea", phoneCode: "82", nationality: "South Korean" },
  { name: "South Africa", phoneCode: "27", nationality: "South African" },
  { name: "Qatar", phoneCode: "974", nationality: "Qatari" },
  { name: "Russia", phoneCode: "7", nationality: "Russian" },
  { name: "Oman", phoneCode: "968", nationality: "Omani" },
  { name: "United Kingdom", phoneCode: "44", nationality: "British" },
  { name: "United States", phoneCode: "1", nationality: "American" },
  { name: "Zambia", phoneCode: "260", nationality: "Zambian" },
  { name: "Zimbabwe", phoneCode: "263", nationality: "Zimbabwean" },
];
